version: '3'

networks:
  soot-site:


services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    hostname: api
    restart: always
    container_name: api
    volumes:
      - ./backend:/app
    networks:
      - soot-site

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: god_nginx
    restart: always
    ports:
      - 8009:8009
      - "1935:1935"  # RTMP port
    volumes:
      - ./nginx/configs/nginx-dev.conf:/etc/nginx/nginx.conf:ro
      - ./backend/logs/nginx:/var/log/nginx
      - ./backend/media/collectstatic/:/collectstatic/
      - ./backend/media/uploads/:/media/
      - ./nginx/tmp/hls:/tmp/hls
    networks:
      - soot-site
    depends_on:
      - backend