version: '3'

networks:
  soot-site:


services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: api
    restart: always
    container_name: api
    volumes:
      - ./backend:/app
    networks:
      - soot-site

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: god_nginx
    restart: always
    ports:
      - 8009:8009
    volumes:
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/logs/nginx:/var/log/nginx
      - ./backend/media/collectstatic/:/collectstatic/
      - ./backend/media/uploads/:/media/
    networks:
      - soot-site
    depends_on:
      - backend
