version: '3'

networks:
  soot_site:

services:
  database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: database
    hostname: database
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - ./postgres/configs/:/configs/
    env_file:
      - ./postgres/configs/postgres.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-p", "5438"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - soot_site

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    hostname: soot-api
    restart: always
    container_name: soot-api
    volumes:
      - ./backend:/app
    networks:
      - soot_site

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: soot-nginx
    restart: always
    ports:
      - "443:443" # HTTP port
      - "1935:1935"  # RTMP port
    volumes:
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/logs/nginx:/var/log/nginx
      - /etc/letsencrypt/live/varleague.ir-0002/fullchain.pem:/etc/letsencrypt/fullchain.pem:ro
      - /etc/letsencrypt/live/varleague.ir-0002/privkey.pem:/etc/letsencrypt/privkey.pem:ro
      - ./backend/media/collectstatic/:/collectstatic/
      - ./backend/media/uploads/:/media/
      - ./nginx/tmp/hls:/tmp/hls
    networks:
      - soot_site
    depends_on:
      - backend