# Generated by Django 5.1.5 on 2025-02-09 17:19

import django.core.validators
import django_ckeditor_5.fields
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('alternate_text', models.CharField(blank=True, help_text='Write about picture for SEO', max_length=110, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(3)], verbose_name='Picture Alternate Text')),
                ('width_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="size of picture's Width", null=True, verbose_name='Picture Width')),
                ('height_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="size of picture's Height", null=True, verbose_name='Picture Height')),
                ('phone_number', models.CharField(db_comment="Stores the site's contact phone number.", help_text='Enter the contact phone number.', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(db_comment="Stores the site's contact email address.", help_text='Enter the contact email address.', max_length=254, verbose_name='Email')),
                ('footer_description', django_ckeditor_5.fields.CKEditor5Field(db_comment='Stores the footer description content.', help_text='Provide a description or additional information for the footer.', verbose_name='Footer Description')),
                ('footer_copyright', models.CharField(db_comment='Stores the copyright information displayed in the site footer.', help_text='Enter the copyright text to be displayed in the footer.', max_length=255, verbose_name='Footer Copyright')),
                ('brand_name', models.CharField(db_comment="Stores the site's brand or company name.", help_text='Enter the brand or company name.', max_length=100, verbose_name='Brand Name')),
                ('site_logo', sorl.thumbnail.fields.ImageField(db_comment="Stores the site's logo image.", help_text='Upload the logo of the site.', upload_to='site/logos/', verbose_name='Site Logo')),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Contents',
                'db_table': 'site_content',
                'db_table_comment': 'Table storing general site content details such as contact information, footer text, and logo.',
            },
        ),
    ]
