# Generated by Django 5.2.1 on 2025-05-20 06:12

import django.core.validators
import django_ckeditor_5.fields
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(db_comment='Stores the unique title of the instance.', help_text='Enter a unique title.', max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, db_comment='Stores the URL-friendly slug derived from the title.', help_text='URL-friendly slug from the title.', max_length=255, unique=True, verbose_name='Slug')),
                ('alternate_text', models.CharField(blank=True, help_text='Write about picture for SEO', max_length=110, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(3)], verbose_name='Picture Alternate Text')),
                ('width_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="size of picture's Width", null=True, verbose_name='Picture Width')),
                ('height_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text="size of picture's Height", null=True, verbose_name='Picture Height')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, db_comment='Stores the detailed rich-text description of the live stream.', help_text='Detailed description of the live stream, including content, features, and schedule.', verbose_name='Description')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, db_comment='Image or thumbnail representing the live stream.', help_text='Upload a representative image or thumbnail for the live stream.', null=True, upload_to='live_streams/%Y/%m/', verbose_name='Stream Image')),
                ('stream_url', models.URLField(blank=True, db_comment='URL where the live stream can be accessed.', help_text='URL for accessing the live stream (e.g., YouTube, Twitch, or custom platform).', max_length=255, validators=[django.core.validators.URLValidator()], verbose_name='Stream URL')),
                ('is_active', models.BooleanField(db_comment='Flag indicating if the live stream is currently active.', default=False, help_text='Indicates whether the live stream is currently active.', verbose_name='Is Active')),
                ('scheduled_at', models.DateTimeField(blank=True, db_comment='Date and time when the live stream is scheduled to start.', help_text='Optional scheduled start time for the live stream.', null=True, verbose_name='Scheduled Time')),
            ],
            options={
                'verbose_name': 'live stream',
                'verbose_name_plural': 'live streams',
                'db_table': 'live_streams',
                'db_table_comment': 'Table storing live stream records.',
                'ordering': ['-scheduled_at', 'title'],
                'indexes': [models.Index(fields=['slug'], name='live_stream_slug_idx'), models.Index(fields=['is_active'], name='live_stream_active_idx')],
            },
        ),
    ]
