# Generated by Django 5.2.1 on 2025-05-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_livestream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
