"""
Django settings for kernel project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
from decouple import Config, RepositoryEnv

config = Config(RepositoryEnv('.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGOUT_REDIRECT_URL = '/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w2)c!*glw4yd!f#l%hnti@m(^dw_55&m23ycm(%g5)quig=7vk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "modeltranslation",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_jsonform",
    "widget_tweaks",
    'django_ckeditor_5',
    'sorl.thumbnail',
    "phonenumber_field",
    'import_export',
    "sage_seo",
    "sage_blog",
    "corporate",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "sage_seo.middleware.slug_swap.OldSlugRedirectMiddleware",
    "sage_seo.middleware.url_redirect.URLRedirectMiddleware",
]

ROOT_URLCONF = "kernel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'corporate.context_processors.site_content',
            ],
            "builtins": [
                "django.templatetags.static",
                "django.templatetags.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = 'kernel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fa"
LANGUAGES = [
    ['en', 'English'],
    ['fa', 'Persian']
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ====================================
# Static and Media Files Configuration
# ====================================
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = 'media/uploads/'
STATIC_ROOT = 'media/collectstatic/'
STATICFILES_DIRS = ('media/static/',)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MODELTRANSLATION_DEFAULT_LANGUAGE = LANGUAGE_CODE


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MODELTRANSLATION_CUSTOM_FIELDS = "django_ckeditor_5.fields.CKEditor5Field"
CKEDITOR_5_STORAGE_BACKEND = "django.core.files.storage.FileSystemStorage"

# ====================================
# Thumbnail and CKEditor Configuration
# ====================================
THUMBNAIL_KVSTORE = 'sorl.thumbnail.kvstores.cached_db_kvstore.KVStore'
THUMBNAIL_DEBUG = True

CKEDITOR_5_STORAGE_BACKEND = "django.core.files.storage.FileSystemStorage"
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "|",
            "link",
            "bulletedList",
            "numberedList",
            "|",
            "outdent",
            "indent",
            "|",
            "blockQuote",
            "imageUpload",
            "|",
            "undo",
            "redo",
            "|",
            "removeFormat",
            "code",
            "codeBlock",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:full",
                "imageStyle:side",
            ],
            "styles": [
                "full",
                "side",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
            ]
        },
    },
}

CKEDITOR_5_CUSTOM_CONFIG = {
    "simpleUpload": {
        "uploadUrl": "uploads/ckeditor/",
    }
}

LOCALE_PATHS = (
    "locale/",
    "locales"
)
